# Generated by Django 3.1.8 on 2022-06-27 09:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tagline', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=255)),
                ('body_text', models.TextField()),
                ('pub_date', models.DateField()),
                ('mod_date', models.DateField(default=datetime.date.today)),
                ('number_of_comments', models.IntegerField(default=0)),
                ('number_of_pingbacks', models.IntegerField(default=0)),
                ('rating', models.IntegerField(default=5)),
                ('authors', models.ManyToManyField(to='app1.Author')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.blog')),
            ],
        ),
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10, verbose_name='Enter your name')),
                ('email', models.EmailField(max_length=254)),
                ('ph_no', models.PositiveIntegerField()),
                ('password', models.CharField(max_length=8)),
                ('address', models.TextField(default='')),
                ('status', models.BooleanField(default=False, verbose_name='Subscription done?')),
                ('date', models.DateField(auto_now=True)),
                ('gender', models.CharField(choices=[('slect gender', 'select gender'), ('Male', 'Male'), ('FEmale', 'female')], default='slect gender', max_length=12)),
                ('profile', models.ImageField(default='', null=True, upload_to='photo')),
            ],
        ),
        migrations.DeleteModel(
            name='product',
        ),
    ]
