# Generated by Django 3.1.8 on 2022-06-29 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('des', models.TextField()),
                ('price', models.IntegerField()),
                ('img', models.ImageField(upload_to='pro')),
                ('review', models.TextField()),
            ],
        ),
    ]
